balancednetwork/balanced-contracts

core_contracts/dex/dex.py
The DEX should track the current amount of BALN held in particular pools. This adds an API that can be called by the dividends score to access this information. This allows it to credit users for their BALN held, but locked up providing liquidity in markets such as BALN / bnUSD.
This introduces a new DictDB to track the quantity, a snapshotting mechanism almost identical to the total supply one, and an external readonly method to retrieve it.
Fixes #153
Addresses DEX component of #146
=> BALN Snapshots (#153)

Balanced Clean Install.ipynb, core_contracts/rewards/rewards.py
Also added toggleStakingEnabled cell in clean install flow.
=> fix getEmission method.

core_contracts/dex/dex.py
Updates input validation in `deposit`/`remove` endpoints, improves error messages.
Additionally, this updates the sICX swap APIs. Before, addresses were left in the active addresses list even if they ran out of funds, if they were filled by swap_icx orders. Now, consider these cases:
1. User A - sends 50 ICX, order sits. User A is earning rewards
2. User B - sends 50 ICX, order sits, User B is earning rewards
3. User C swaps 60 sICX at a 1-1 price. Both user A and B are removed from active addresses
4. User B cancels order - no change
5. User A sends 60 ICX - earning rewards
6. User C swaps 5 ICX - user a still earning rewards
Fixes #168
=> Handle purging addresses in ICX queue and update input validation

Balanced Clean Install.ipynb, core_contracts/governance/governance.py, token_contracts/bwt/tokens/IRC2.py, token_contracts/bwt/worker_token.py
Also added a setAdmins method to governance.
Fixes #181
=> added distribution method to BALW token.

core_contracts/dividends/dividends.py
* Fix the possibility of reentrancy attack in the dividends distribution to daofund
=> Change distribution status and then distribute to daofund

core_contracts/dex/dex.py
- Removes unused `old_price` param
- Make external read methods readonly
- Remove sICX/ICX order id before transferring ICX
=> [audit] Dex audit feedback from the ICON team

core_contracts/governance/governance.py
Removed use of RECIPIENTS constant in pool creation.
=> fixed pool creation.

Balanced Clean Install.ipynb, core_contracts/rewards/RewardData.py, core_contracts/rewards/rewards.py
Unstick rewards. add rewards progress eventlog.
=> finish rewards. add eventlog.

token_contracts/baln/balance.py
Fix the unresolved reference exception
=> Add missing getBalnPrice interface

core_contracts/dex/dex.py
Adds a method to inspect user's balance snapshots. This will help debug the rewards distribution.
=> Add additional method to inspect snapshots

core_contracts/dex/dex.py, core_contracts/governance/governance.py, core_contracts/governance/interfaces.py
- added method to add active users to a pool in dex
- the method is called via intercontract call from governance SCORE
Fixes #216
=> Dex add lp addresses

core_contracts/dex/dex.py
https://www.python.org/dev/peps/pep-0008/#programming-recommendations
=> None should always be done with 'is' or 'is not', never the equality operators

core_contracts/dex/dex.py
Use withdrawal locks of 1 day on supplied liquidity
=> Restore withdrawal locks

Balanced Clean Install.ipynb, core_contracts/dividends/dividends.py, core_contracts/loans/loans/loans.py
Start dividends recording the amount of fees received daily.
=> Daily div snapshot

token_contracts/baln/balance.py, token_contracts/bnUSD/bnUSD.py, token_contracts/sicx/sicx.py
on_update added to bnUSD, BALN, and sICX
=> add on_update method to move tokens to new div SCORE.

Balanced Clean Install.ipynb, core_contracts/governance/governance.py, core_contracts/governance/interfaces.py
Added setter for redemption fee to governance.
=> Add redemption fee setter to governance.

core_contracts/dex/dex.py
Get BALN balance in a pool without TWA by default.
=> Take baln snapshots without TWA

core_contracts/governance/data_objects.py, core_contracts/governance/governance.py, tests/test_unit_governance.py
* Introduce ProposalDB to store details related to proposal in a single class
=> Use separate DB to store details about proposal

Balanced Clean Install.ipynb, core_contracts/governance/data_objects.py, core_contracts/governance/governance.py, core_contracts/governance/interfaces.py, core_contracts/governance/utils/consts.py, tests/test_unit_governance.py
A first draft for voting functionality with only the vote to enable dividends distribution possible.
=> Added voting to the governance SCORE

core_contracts/staking/staking.py
User needs to claim the unstake amount once it is ready to claim.
User can sends ICX directly to staking contract instead of calling stakeICX function to get sICX.(issue #224 )
=> Claim for unstake amount

core_contracts/governance/governance.py, core_contracts/governance/interfaces.py, core_contracts/loans/loans/loans.py, core_contracts/loans/utils/checks.py, core_contracts/rebalancing/rebalancing.py
Added a rebalancing_only decorator to the retireRedeem method.
Eliminated the transfer of sICX from the Rebalancing SCORE to Loans SCORE and back.
Small code optimizations and clean up.
=> Refine rebalancing

core_contracts/dex/dex.py
Fixes #252 - scales the bnUSD value correctly for sICX pools.
=> sICX pool correct bnUSD value

core_contracts/governance/data_objects.py, core_contracts/governance/governance.py
The major tasks are:
- Created separate vardb for counting the voters who are against as well as with the proposal.
- Created an external function to return those values.
=> api created for number of voters

core_contracts/governance/governance.py
- Proposers added in checkVote function
- castVote stake variable changed to total_vote
- revert message modification
=> 263 api for number of voters

Balanced Clean Install.ipynb, core_contracts/governance/governance.py, core_contracts/rebalancing/rebalancing.py
Also grouped the setter methods.
Added a couple cells to the notebook to define a vote with a description.
=> removed duplicate method.
